### ISSUE TITLE
Does strips support quantifiers?

### ISSUE THREAD

**Issue by boramalper** [primaryobjects/strips#10]
Does strip support quantifiers?

I am getting the following error

```
undefined:1483
      throw peg$buildStructuredError(
      ^
peg$SyntaxError: Expected "(", ")", ":", ";", "and", "not", [\n\r\t ], [a-zA-Z0-9\-], or end of input but "?" found.
    at peg$buildStructuredError (eval at compile (/home/bora/finitech/planner/strips/node_modules/pegjs/lib/compiler/index.js:67:29), <anonymous>:342:14)
    at Object.peg$parse [as parse] (eval at compile (/home/bora/finitech/planner/strips/node_modules/pegjs/lib/compiler/index.js:67:29), <anonymous>:1483:13)
    at /home/bora/finitech/planner/strips/node_modules/strips/strips.js:35:33
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
  message: 'Expected "(", ")", ":", ";", "and", "not", [\\n\\r\\t ], [a-zA-Z0-9\\-], or end of input but "?" found.',
  expected: [
    { type: 'literal', text: '(', ignoreCase: false },
    { type: 'literal', text: ')', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'literal', text: 'and', ignoreCase: false },
    { type: 'literal', text: 'not', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    { type: 'literal', text: ')', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: ';', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'literal', text: '(', ignoreCase: false },
    { type: 'literal', text: ')', ignoreCase: false },
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    { type: 'literal', text: ';', ignoreCase: false },
    { type: 'literal', text: ':', ignoreCase: false },
    { type: 'end' }
  ],
  found: '?',
  location: {
    start: { offset: 4082, line: 155, column: 18 },
    end: { offset: 4083, line: 155, column: 19 }
  },
  name: 'SyntaxError'
}
```

where line 155 is:

```pddl
    (:goal (and
        (exists (?ps - park) (and  ;; <<<< line 155
            (IsAt Car ?ps)
        ))
    ))
```

- node: 12.14.1
- strips: 0.0.10
- pegjs: 0.10.0

I would be happy to provide the files as well if needed.

Regards,
Bora

/cc @theodor1289

**Comment by amariucaitheodor** [comment]
I haven't checked but you might be able to find your answer at the [domain grammar file](https://github.com/primaryobjects/strips/blob/master/strips/grammar/grammar-domain.txt) or at the [problem grammar file](https://github.com/primaryobjects/strips/blob/master/strips/grammar/grammar-problem.txt) which are used to parse the domain.pddl and problem.pddl files I believe.

**Comment by boramalper** [comment]
> I haven't checked but you might be able to find your answer at the [domain grammar file](https://github.com/primaryobjects/strips/blob/master/strips/grammar/grammar-domain.txt) or at the [problem grammar file](https://github.com/primaryobjects/strips/blob/master/strips/grammar/grammar-problem.txt) which are used to parse the domain.pddl and problem.pddl files I believe.

A search for `forall` and `exists` returns nothing in the grammar files you have linked.

@primaryobjects Can you confirm?

**Comment by primaryobjects** [comment]
That is correct, it not supported in this version. Please feel free to fork a copy of the project if you can add this feature. Thanks!
